version: '2'

services:

  fluentd:
    build: ./fluentd
    image: jazzwang/td-agent:3
    hostname: fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/etc:/etc/td-agent
      - ./fluentd/output:/data
  
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=myweb
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/app:/app
